In [1]:
import pandas as pd

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
df = pd.DataFrame(data = d)

In [4]:
df['size'].nunique()

3

In [5]:
df['size'].value_counts()

size
Medium    5
Small     4
Large     3
Name: count, dtype: int64

In [6]:
df['size'].unique()

<StringArray>
['Small', 'Medium', 'Large']
Length: 3, dtype: str

ORDINAL ENCODING ON SIZE

In [10]:
sizes = ['Small', 'Medium', 'Large']

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
enc = OrdinalEncoder(categories= [sizes])

In [ ]:
enc.fit_transform(df[['size']])     #it is gonna make an array but we need it in our dataset

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.]])

In [ ]:
df.head()   #nothing has changed

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [ ]:
df['size'] = enc.fit_transform(df[['size']])    #that's how it's implemented in the dataset

In [16]:
df.head(10)

     sales          city  size
0   100000         Tampa   0.0
1   222000         Tampa   1.0
2  1000000       Orlando   2.0
3   522000  Jacksonville   2.0
4   111111         Miami   0.0
5   222222  Jacksonville   1.0
6  1111111         Miami   2.0
7    20000         Miami   0.0
8    75000       Orlando   1.0
9    90000       Orlando   1.0